allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  esbuild: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
